### ISSUE TITLE
UnboundLocalError: local variable 'self' referenced before assignment

### ISSUE THREAD

**Issue by jeveli** [dawesry/porpo#29]
Gets a error code.
How can i look at the exported data? Only thing i find under the exported track is filenames that ends with .ff1pkl
Example: cardata.ff1pkl, driverinfo.ff1pkl
And the error code is:
UnboundLocalError: local variable 'self' referenced before assignment

**Comment by dawesry** [comment]
You can view exported graphs by navigating to your export directory. By default this is in your Documents folder.

Currently there is no option to view data in a CSV format.

Can you explain what you're doing when the error happens?

**Comment by jeveli** [comment]
Yeah when i navigate to my document folder where all the files are exported, every file have a filename_extension:  .ff1pkl
How to open these?
![image](https://user-images.githubusercontent.com/7755806/180839819-3072e728-5e41-4f66-8116-be54859af838.png)

**Comment by dawesry** [comment]
Those are FastF1 packages. You're in the cache folder, and shouldn't be. 

Navigate to your export folder instead to view any graphs.

**Comment by jeveli** [comment]
When i push the analyze button a windows pops up for about 1 sec and disappears, and i can't find the export folder anywhere. i don't have a ~/Documents/F1 Data Analysis/Export/

This is the terminal after i push the button. 
![image](https://user-images.githubusercontent.com/7755806/180841676-d392eb97-4861-48d7-9e3a-69986f21074e.png)

**Comment by jeveli** [comment]
When trying to set a export directory, nothing happens, nothing popups.
When trying the cache directory, i can choose a folder, not with export.
![image](https://user-images.githubusercontent.com/7755806/180842614-1426666c-6dca-4cd3-940a-b640614b8afe.png)

**Comment by dawesry** [comment]
That's very strange. I'll take a look and make some fixes. Very much appreciated!

**Comment by jeveli** [comment]
Great will test it when it is available

**Comment by dawesry** [comment]
There should now be a `data` folder within the `porpo` project folder. Inside that folder is your `export` folder.

**Comment by jeveli** [comment]
Still does not work, no export folder. In the previous version, i could put the export folder manually in the Main.py and it worked.
![image](https://user-images.githubusercontent.com/7755806/181430672-99874ea3-3587-440e-8ddc-e5fef849ed83.png)

**Comment by dawesry** [comment]
Porpo handles the folders for you. You shouldn't be moving folders around. 

It checks to see if the path is created, and if not, it creates it. The default save path in 1.4.1 is `porpo/data/export`.

Are you running CLI or GUI script?

Looking quickly at that that error, there's an extra "/" somewhere, should be a simple fix.

**Comment by dawesry** [comment]
Change line 33 of `porpo/scripts/gui.py` from 

`default = './data/export/'`

to 

`default = './data/export'`

and run
